# Generated by Django 3.2.3 on 2021-05-31 18:59

from django.db import migrations, models

from website.models import options


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, null=True)),
                ('apelido', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('pergunta1', models.CharField(max_length=6, null=True)),
                ('pergunta2', models.CharField(max_length=5, null=True)),
                ('pergunta3', models.CharField(max_length=1, choices=options()[0], blank=False, default='Unspecified')),
                ('pergunta4', models.CharField(max_length=1, choices=options()[1], blank=False, default='Unspecified')),
                ('pergunta5', models.CharField(max_length=1, choices=options()[2], blank=False, default='Unspecified')),
                ('pergunta6', models.CharField(max_length=1, choices=options()[3], blank=True, default='Unspecified')),
                ('pergunta7', models.IntegerField(default=1)),
                ('pergunta8', models.CharField(max_length=1, choices=options()[4], blank=True, default='Unspecified')),
                ('pergunta9', models.CharField(max_length=1, choices=options()[4], blank=True, default='Unspecified')),
            ],
        ),
    ]
