# Generated by Django 3.2.3 on 2021-05-31 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210531_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='pergunta1',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta2',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta3',
            field=models.CharField(choices=[('1', 'Vermelho'), ('2', 'Azul'), ('3', 'Laranja')], default='Unspecified', max_length=1),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta4',
            field=models.CharField(choices=[('1', 'Magenta'), ('2', 'Roxo'), ('3', 'Amarelo')], default='Unspecified', max_length=1),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta5',
            field=models.CharField(choices=[('1', 'Vermelho'), ('2', 'Verde'), ('3', 'Azul'), ('4', 'Amarelo')], default='Unspecified', max_length=1),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta6',
            field=models.CharField(choices=[('1', 'Spring'), ('2', 'Winter'), ('3', 'Fall'), ('4', 'Azul'), ('5', 'Summer')], default='Unspecified', max_length=1),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta7',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta8',
            field=models.CharField(choices=[('1', 'Cores Frias'), ('2', 'Cores Quentes')], default='Unspecified', max_length=1),
        ),
        migrations.AddField(
            model_name='quizz',
            name='pergunta9',
            field=models.CharField(choices=[('1', 'Cores Frias'), ('2', 'Cores Quentes')], default='Unspecified', max_length=1),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='apelido',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='quizz',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
