# Generated by Django 3.2.3 on 2021-06-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210601_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Paleta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cor1', models.CharField(max_length=7)),
                ('cor2', models.CharField(max_length=7)),
                ('cor3', models.CharField(max_length=7)),
                ('cor4', models.CharField(max_length=7)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.autor')),
                ('categoria', models.ManyToManyField(blank=True, related_name='Paletas', to='website.Categoria')),
            ],
        ),
    ]
