# Generated by Django 3.2.3 on 2021-06-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_autor_categoria_paleta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='paleta',
            old_name='autor',
            new_name='author',
        ),
    ]
