# Generated by Django 3.2.3 on 2021-06-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210601_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25, null=True)),
                ('apelido', models.CharField(max_length=25, null=True)),
                ('telefone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=75, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
