# Generated by Django 3.2.3 on 2021-06-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(choices=[('1', 'Claro'), ('2', 'Médio'), ('3', 'Ruim')], default='Unspecified', max_length=1)),
                ('navegacao', models.CharField(choices=[('1', 'Claro'), ('2', 'Médio'), ('3', 'Ruim')], default='Unspecified', max_length=1)),
                ('velocidade', models.CharField(choices=[('1', 'Claro'), ('2', 'Médio'), ('3', 'Ruim')], default='Unspecified', max_length=1)),
                ('geral', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
